# Generated by Django 3.2.12 on 2023-11-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eams.student'),
        ),
    ]
