# Generated by Django 4.2.7 on 2023-11-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0002_profile_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semesterregistrationform',
            table='SemesterRegistrationForm',
        ),
    ]
