# Generated by Django 4.2.5 on 2023-09-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0002_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
