# Generated by Django 4.2.5 on 2023-09-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0003_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eams.unit'),
            preserve_default=False,
        ),
    ]
