# Generated by Django 4.2.3 on 2023-09-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0003_remove_programme_del_date_remove_programme_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
    ]
