# Generated by Django 4.2.5 on 2023-09-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0004_remove_student_department_remove_unit_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometric_data',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exam_attendace',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='biometric_data',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eams.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_attendace',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eams.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eams.student'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('cell_phone', models.CharField(max_length=20, null=True)),
                ('rol_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20)),
                ('is_staff', models.BooleanField(default=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eams.unit')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
