# Generated by Django 4.2.3 on 2023-09-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0004_alter_unit_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biometric_data',
            table='biometric_data',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='course_programme',
            table='course_programme',
        ),
        migrations.AlterModelTable(
            name='course_semester',
            table='course_semester',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='education_level',
            table='education_level',
        ),
        migrations.AlterModelTable(
            name='exam_attendace',
            table='exam_attendace',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='programme',
            table='programme',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='semester',
        ),
        migrations.AlterModelTable(
            name='year_of_study',
            table='year_of_study',
        ),
    ]
