# Generated by Django 4.2.5 on 2023-11-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0005_semester_semester_end_at_semester_semester_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Core', 'Core'), ('None Core', 'None Core')], default='Core', max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='semesterregistration',
            name='semester_registration_status',
            field=models.CharField(default='registered', max_length=100),
        ),
    ]
