# Generated by Django 4.2.5 on 2023-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0005_remove_biometric_data_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
