# Generated by Django 4.2.5 on 2023-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0006_course_credit_course_type_alter_semester_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
