# Generated by Django 4.2.5 on 2023-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0007_remove_payment_status_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
