# Generated by Django 4.2.5 on 2023-11-29 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eams.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eams', '0008_payment_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('cell_phone', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(default=eams.models.Staff.default_depertment, on_delete=django.db.models.deletion.CASCADE, to='eams.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
