# Generated by Django 4.2.5 on 2023-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0009_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=1),
        ),
    ]
