# Generated by Django 4.2.5 on 2023-11-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0010_staff_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_staff',
        ),
    ]
