# Generated by Django 3.2.12 on 2023-12-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0013_rename_course_work_student_course_work_course_work_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course_work',
            name='course',
            field=models.IntegerField(null=True),
        ),
    ]
