# Generated by Django 3.2.12 on 2023-12-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0015_remove_student_course_work_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam_attendace',
        ),
    ]
