# Generated by Django 3.2.12 on 2023-12-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0016_delete_exam_attendace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_attendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_exam', models.CharField(choices=[('ue', 'University Exam'), ('se', 'Supplementary Exam'), ('t1', 'Test One'), ('t2', 'Test Two')], default='ue', max_length=2)),
                ('booklet_number', models.CharField(max_length=100)),
                ('signin_fingerprint', models.BinaryField()),
                ('signout_fingerprint', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biometric_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eams.biometric_data')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eams.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eams.programme')),
            ],
            options={
                'db_table': 'exam_attendace',
            },
        ),
    ]
