# Generated by Django 3.2.12 on 2023-12-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0019_auto_20231231_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_attendace',
            name='exam_status',
            field=models.CharField(default='on progress', max_length=100),
        ),
    ]
