# Generated by Django 3.2.12 on 2024-01-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0020_exam_attendace_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_attendace',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eams.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_attendace',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eams.semester'),
            preserve_default=False,
        ),
    ]
