# Generated by Django 4.2.5 on 2024-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0021_auto_20240101_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_exam_attendence_record',
            name='booklet_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
