# Generated by Django 4.2.5 on 2024-01-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0022_alter_final_exam_attendence_record_booklet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_exam_attendence_record',
            name='signin_flag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='final_exam_attendence_record',
            name='signout_flag',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
